feature: added south african reserve scraper
sgoldfarb2/scraper-infra pull request #11
Opened 2023-12-04 21:21 UTC by SFJohnson24

added south african reserve scraper

2023-12-12 21:46 UTC, nattiechan requested changes
Before you address any comments regarding the code, I suspect the URL is incorrect.

With the URL you provided in the scraper, they only show circulars up to 2015, which does not seem right.

When I click "Bank Circulars" at the bottom right under `Publications Categories`, it opens a different page (https://www.resbank.co.za/en/home/publications/prudential-authority/banks-circulars) that seems to have more recent circulars available.

@sgoldfarb2 can we confirm which URL is correct?

2023-12-12 21:46 UTC, nattiechan commented on scrapers/south_african_reserve.py
> +    south_african_reserve_scraper()
Need a new line at the end of the file

2023-12-12 21:46 UTC, nattiechan commented on scrapers/utils.py
> +        if not is_pdf and download_link[-4:] != '.pdf':
I requested a similar change in a different PR: https://github.com/sgoldfarb2/scraper-infra/pull/10#discussion_r1423104472

For the purpose of keeping changes clean and not co-mingling with each other, let's take this change out.

2023-12-12 21:46 UTC, nattiechan commented on scrapers/utils.py
> +import requests
same here

2023-12-13 19:59 UTC, nattiechan requested changes

2023-12-13 19:59 UTC, nattiechan commented on .vscode/settings.json
> -      "source.organizeImports": true
I also noticed this change with newer versions of VS code. Can we double check what this change is about before committing to this change?

2023-12-13 19:59 UTC, nattiechan commented on scrapers/south_african_reserve.py
> +        # link=pdf_link.get_attribute("href")
Can we clean up unused code please?

2023-12-13 19:59 UTC, nattiechan commented on scrapers/utils.py
> +            raise TypeError("File extension does not match content type.")
Has this change been included in another PR?

2023-12-13 20:00 UTC, nattiechan commented
@SFJohnson24 have you confirmed with @sgoldfarb2 regarding the URL?

2023-12-13 20:30 UTC, SFJohnson24 commented on scrapers/south_african_reserve.py
> +        # link=pdf_link.get_attribute("href")
removed

2023-12-13 20:31 UTC, SFJohnson24 commented on scrapers/utils.py
> +            raise TypeError("File extension does not match content type.")
this change is in the bank of ghana PR as well I believe

2023-12-13 20:59 UTC, nattiechan approved these changes
:tada:

2023-12-15 01:05 UTC, jiedong111 approved these changes
LGTM!

2023-12-15 16:47 UTC, merged