feat(infra): Initial setup of CDK repo, basic Lambda DDB SNS
sgoldfarb2/scraper-infra pull request #2
Opened 2023-11-19 15:10 UTC by jiedong111

This PR includes the initial setup of our CDK repo along with some base IaC including some Lambda functions, a state machine, and a dynamodb table. This should give an overview of how to interact with CDK resources across various stacks that we create to separate concerns when it comes to different facets of our application.

In order to provision resources locally and test infrastructure, you'll have to install CDK and bootstrap it with your AWS environment. You can take a look at the instructions in README.md for a more detailed overview on how to do so.

2023-11-19 18:51 UTC, nattiechan requested changes
This looks great so far! Good work for setting this up! I can imagine this is not easy at all.

One overall comment - We need _a lot more comments/docstring_ on what each file and/or function is doing. You will be the subject expert in AWS CDK for this project, but we do not want to create a single point of failure so if you are not available, others can navigate around this infrastructure and make changes as needed.

Some of the things that stood out to me:

- files like validation.py and notification.py.. why do we need them? What do they actually do?
- `shared-recources.ts` could use a lot more comment/docstring, explaining what the functions are doing

2023-11-19 18:51 UTC, nattiechan commented on lib/database-stack.ts
> +        partitionKey: {name: 'bank_name', type: dynamodb.AttributeType.STRING},
Will this be the same partition key that we discussed in the meeting? I forgot what it is exactly but I think it is more than just the bank name?

2023-11-19 18:51 UTC, nattiechan commented on lib/shared-resources.ts
> +    // );
Do we need this code?

2023-11-19 18:51 UTC, nattiechan commented on lib/shared-resources.ts
> +            runtime: lambda.Runtime.PYTHON_3_9,
I am using 3.12 in my PR. Would that be an issue? Or you want me to downgrade? (prob prefer 3.10 minimum?)

2023-11-19 18:51 UTC, nattiechan commented on lib/shared-resources.ts
> +            runtime: lambda.Runtime.PYTHON_3_9,
Same here

2023-11-19 18:51 UTC, nattiechan commented on lib/shared-resources.ts
> +            }
I have not read the docs much, and I am wondering how this `environment` variable is used? As we have more and more scrapers, how would it affect the map here?

2023-11-19 18:51 UTC, nattiechan commented on lib/shared-resources.ts
> +            }
Do we plan to use one table per bank? Or a table by usage? (i.e. one table for notification, one table for scraper runs... etc)

2023-11-19 18:51 UTC, nattiechan commented on lib/shared-resources.ts
> +        resultPath: '$.hashedUrl',
Do we plan to store the URL in the DB? Or just in the scraper file is suffice?

2023-11-19 18:51 UTC, nattiechan commented on lib/shared-resources.ts
> +        timeout: cdk.Duration.seconds(300),
What is the max timeout we can have here?

2023-11-19 18:51 UTC, nattiechan commented on lib/shared-resources.ts
> +    new s3.Bucket(this, 'testbucket12341%13x', {
Should we put `'testbucket12341%13x'` or something along those lines in `.env` as well?

2023-11-19 18:51 UTC, nattiechan commented on test/scraper-infra.test.ts
> +});
If this test is not ready, let's remove the dead code for now

2023-11-19 18:51 UTC, nattiechan commented on README.md
We may want to move the CDK-specific instruction into a different `.md` file, so we can use the `README` for more general epic-related matters

2023-11-19 19:07 UTC, jiedong111 commented on lib/database-stack.ts
> +        partitionKey: {name: 'bank_name', type: dynamodb.AttributeType.STRING},
Yea, this ddb table setup was made prior to the meeting. I'm looking to get the partition key set straight sometime later today, but wanted to get this PR up so we can merge in the scraper stuff. I'll leave a comment on it in the code so we don't lose track of this

2023-11-19 19:09 UTC, jiedong111 commented on lib/shared-resources.ts
> +    // );
I left it in as a note for myself for setting up more complex role-based access control with CDK, but I'll remove it and just note it down somewhere for myself

2023-11-19 19:10 UTC, jiedong111 commented on lib/shared-resources.ts
> +            runtime: lambda.Runtime.PYTHON_3_9,
It looks like Lambda only supports up to 3.11, so we'd have to downgrade from 3.12 to 3.11, I only provisioned these handlers with 3.9 to match the examples I was seeing since I was exploring things. I don't think running it in 3.11 would change anything

2023-11-19 19:12 UTC, jiedong111 commented on lib/shared-resources.ts
> +            }
The environment variable for lambdas let you freely supply environment variables to the state of a particular lambda function, so this is just providing 'Bank of Kenya' as the bank for this specific scraper. We could literally hard code the relevant bank into the environment of each scraper handler if we needed to depending on our implementation

2023-11-19 19:18 UTC, jiedong111 commented on lib/shared-resources.ts
> +        timeout: cdk.Duration.seconds(300),
In a state machine, the timeout can be a year I think. We're going to transition to using just Lambda and Dynamodb streams to trigger other Lambdas, so our max timeout without using a state machine would be 15 minutes. 

If we find we need a longer timeout on some operation for some reason, we can transition that part specifically to a step function but step functions apply cost based on state changes and are much less generous than the free tier of lambda so if we can keep it to lambda/dynamo that would be best

2023-11-19 19:20 UTC, jiedong111 commented on lib/shared-resources.ts
> +        resultPath: '$.hashedUrl',
I think based on the discussion we had with Alex, we're going to be storing:

> UUID,
> date_updated,
> hash_of_file,
> bank_name,

in the table and running with a composite key of UUID#hash_of_file and a range key of AWSTimeStamp

2023-11-19 19:22 UTC, jiedong111 commented on lib/shared-resources.ts
> +            }
I think we're going to be using 1 dynamo table to store the bank data, use dynamo streams to trigger lambdas off changes to that table, then users would be informed with SNS and SQS. We'd have another microservice that would handle user subscriptions and consume from the events that we push from this microservice through SNS into SQS in order to send notifications.

2023-11-19 19:23 UTC, jiedong111 commented on lib/shared-resources.ts
> +    new s3.Bucket(this, 'testbucket12341%13x', {
I think test bucket is just a string that you provide that appends to the actual bucket name when CDK provisions it. Having that string exposed here isn't exposing any sensitive information

2023-11-19 19:28 UTC, jiedong111 commented
Currently working through your comments and adjusting the PR, thanks for taking the time Nattie! 

'Validation.py' and 'notification.py' are additional lambda functions that were made as a proof of concept of setting up a step function. Since we're moving away from step functions they aren't strictly needed right now. I think they might be useful to keep around though just to emphasize that lambda functions should serve an individual purpose, so we have one function for scraping, one function for validating the scraped information against our table, and one function that sends a notification to SNS.

2023-11-19 20:01 UTC, nattiechan commented on lib/database-stack.ts
> +        partitionKey: {name: 'bank_name', type: dynamodb.AttributeType.STRING},
Yep this is something that we can address in a follow-up PR

2023-11-19 20:02 UTC, nattiechan commented on lib/shared-resources.ts
> +            runtime: lambda.Runtime.PYTHON_3_9,
I will downgrade the environment to 3.11. Let's set that for AWS

2023-11-19 20:03 UTC, nattiechan commented on lib/shared-resources.ts
> +            }
Got it. Let's move `{"BANK": 'Bank of Kenya'}` example to a comment above L71 here and change the environment back to what we expect for now (probably `{}`?)

2023-11-19 20:06 UTC, nattiechan commented on lib/shared-resources.ts
> +            }
This may warrant further investigation re: price etc, but we may want to look into the possibly of having a table that has all executed scraper runs (both success or fail), and then another table that contains the information of the last success run and the `md5hash` of the file. I wonder if the cost of the lookup would be less and the cost of write is negligible

2023-11-19 20:07 UTC, nattiechan commented on lib/shared-resources.ts
> +        timeout: cdk.Duration.seconds(300),
Let's set this to 5 minutes for now then. Though a comment on 300 seconds = 5 minutes and the max is 15 mins would be helpful

2023-11-19 20:08 UTC, nattiechan commented on lib/shared-resources.ts
> +    new s3.Bucket(this, 'testbucket12341%13x', {
Okay. Eventually we may want to have a more "official" name other than test bucket in there

2023-11-19 20:14 UTC, nattiechan commented on CDK.md
> +I'd recommend following the
typo?

2023-11-19 20:14 UTC, nattiechan commented on CDK.md
> +## How to make it work
For a follow-up PR: consider added a step-by-step instruction, or a link to said information, on how to set things up

2023-11-19 20:14 UTC, nattiechan commented on bin/scraper-infra.ts
> +   * and Region that are implied by the current CLI configuration. */
We uncommented the next line already

```suggestion
  /* Specialize this stack for the AWS Account
   * and Region that are implied by the current CLI configuration. */
```

2023-11-19 20:14 UTC, nattiechan commented on lib/database-stack.ts
> +//stack for database, RDS, DDB tables etc
Dumb question: what is a stack?

2023-11-19 20:17 UTC, nattiechan commented
> 'Validation.py' and 'notification.py' are additional lambda functions that were made as a proof of concept of setting up a step function. Since we're moving away from step functions they aren't strictly needed right now. I think they might be useful to keep around though just to emphasize that lambda functions should serve an individual purpose, so we have one function for scraping, one function for validating the scraped information against our table, and one function that sends a notification to SNS.

I am not a huge fan of leaving dead code in the main branch. One thing you can do to preserve the information is to have a separate branch in this repo, put the code where they should go with some information in the commit on how the information should be consumed.

Of course, another way is to have a separate markdown that logs your findings on how to set up step function (that would be amazing too!)

2023-11-19 20:34 UTC, jiedong111 commented on lib/database-stack.ts
> +//stack for database, RDS, DDB tables etc
Since CDK compiles into Cloudformation templates, it uses a lot of similar syntax. A stack in CDK corresponds to a stack in CloudFormation which is basically a bundle of logical resources that CloudFormation takes and translates into/provisions actual physical infrastructure for.

2023-11-19 20:36 UTC, jiedong111 commented
My concern with removing 'scraper.py', 'validation.py', and 'notification.py' is that without them the state machine currently represented in the code won't actually do anything. They're the lambda functions that are referenced by the current lambda handlers defined in 'shared-resources-stack'. I probably should have been more clear in that they're not strictly necessary for what we'd be doing in the future, but they are necessary for the code as is to run properly once you deploy

2023-11-19 20:45 UTC, nattiechan commented on lib/shared-resources.ts
> +            runtime: lambda.Runtime.PYTHON_3_9,
bump on this

2023-11-19 20:45 UTC, nattiechan commented on lib/shared-resources.ts
> +            runtime: lambda.Runtime.PYTHON_3_9,
this as well

2023-11-19 20:46 UTC, nattiechan commented on src/notification.py
> +    return('success?')
Miss new line at the end of the file (Python linting standards). Same for all `.py` files in this PR

2023-11-19 20:48 UTC, nattiechan reviewed
Would again, appreciate some comments/docstring in `notification.py` and `validation.py` on the purposes of the files

2023-11-19 21:09 UTC, jiedong111 commented
> Would again, appreciate some comments/docstring in `notification.py` and `validation.py` on the purposes of the files

Python files should be adjusted, also updated the runtime on the lambda handlers. Tell me if anything else stands out!

2023-11-19 21:50 UTC, nattiechan approved these changes
Not sure if you want Sabrina to take a look at this as well, and just one last thing before merging

2023-11-19 21:50 UTC, nattiechan commented on lib/shared-resources.ts
> +            runtime: lambda.Runtime.PYTHON_3_9,
Sorry I missed this - we will want to change this to 3.11 as well if possible

2023-11-19 22:49 UTC, jiedong111 commented
I think we should wait till @sgoldfarb2 signs off, adjusted the runtime for 'notification.py'.

2023-11-21 17:31 UTC, sgoldfarb2 approved these changes
this all looks great to me! my only additional (probably silly) question is that this is already setting up a real dynamoDB table, yes? So is there a situation where we could accidentally get ourselves in a pickle with $ if we had say...a hackathon to make 240 scrapers over a weekend and folks were running them often to test them?

2023-11-21 17:31 UTC, sgoldfarb2 commented on CDK.md
> +## How to make it work
Definitely +1 to this, it definitely looks intimidating for someone just coming in

2023-11-21 17:31 UTC, sgoldfarb2 commented on lib/database-stack.ts
> +        partitionKey: {name: 'bank_name', type: dynamodb.AttributeType.STRING},
would you mind even adding a ticket for this too on the scraper project board @jiedong111 ? this way it can't get lost in all the new added work

2023-11-21 18:01 UTC, jiedong111 commented
>this all looks great to me! my only additional (probably silly) question is that this is already setting up a real dynamoDB table, yes? So is there a situation where we could accidentally get ourselves in a pickle with $ if we had say...a hackathon to make 240 scrapers over a weekend and folks were running them often to test them?

The CDK repo will deploy actual resources, but it's configured and bootstrapped for someone's individual credentials. At some point if we have a lot of people working on the infrastructure, we'd have to set up a developer account or some kind of access control to give them access to an existing infrastructure. Since we're only setting things up right now, the way the repo is built it's intended that if an individual contributor wants to mess around with/test the infrastructure they would have to bootstrap their own environment and provide their own credentials. Our scraper local testing doesn't require any deployment to work though, so unless someone manages to bootstrap their environment and deploy accidentally they wouldn't incur any costs, and if they did it would be to their personal AWS accounts. I think it's worth making a bold warning on in CDK.md about that though, so people make sure to properly tear down any environments that they spin up if they go to the trouble of setting things up.

>would you mind even adding a ticket for this too on the scraper project board @jiedong111 ? this way it can't get lost in all the new added work

Just to clarify here, do you mean a ticket for setting up our dynamo tables? But I'd definitely be willing to set up a ticket for it in the scraper project board

2023-11-21 18:12 UTC, merged

2023-11-21 22:15 UTC, nattiechan commented
> So is there a situation where we could accidentally get ourselves in a pickle with $ if we had say...a hackathon to make 240 scrapers over a weekend and folks were running them often to test them?

@sgoldfarb2 as long as:

- The devs test scrapers locally per instructions in my PR
- The scrapers do not connect to AWS in any way (no read/write to/from DynamoDB and s3 bucket)

Then the only concern is devs accidentally bombard the website too much, which I already cautioned in the docs