docs(contrib): update contributing docs
sgoldfarb2/scraper-infra pull request #6
Opened 2023-11-29 22:36 UTC by jpettis1

Based on feedback for environment setup and common issues, updating the environment setup steps to include resolving playwright dependency issues and Python interpreter setup in VS Code.

2023-11-29 22:44 UTC, nattiechan requested changes
Thank you! Just a couple things

2023-11-29 22:44 UTC, nattiechan commented on CONTRIBUTING.md
> +- Check to make sure playwright is installed in your virtual envionrment: `$ pipenv run pip list`
typo

```suggestion
- Check to make sure playwright is installed in your virtual envionment: `$ pipenv run pip list`
```

also - can you specify what folks should be looking for - `pytest-playwright`? or `playwright` on the list? (may want to clarify that)

2023-11-29 22:44 UTC, nattiechan commented on CONTRIBUTING.md
> +  - Select the interpreter referenced in the project's virtual environment:`Python 3.11.6('scraper-infra...') <path> PipEnv`
Can you move this to below the paragraph, after L53? I don't think we should assume everyone is going to be using VS code

2023-11-29 23:25 UTC, jpettis1 commented on CONTRIBUTING.md
> +- Check to make sure playwright is installed in your virtual envionrment: `$ pipenv run pip list`
Absolutely. This is complete and pushed.

2023-11-29 23:26 UTC, jpettis1 commented on CONTRIBUTING.md
> +  - Select the interpreter referenced in the project's virtual environment:`Python 3.11.6('scraper-infra...') <path> PipEnv`
Yes, that makes complete sense. This is now pushed.

2023-11-29 23:29 UTC, nattiechan approved these changes
Thanks!

2023-12-01 19:06 UTC, willhack approved these changes
LGTM 🚀

2023-12-01 19:46 UTC, merged