Feature/gh 29 bank of zambia scraper
sgoldfarb2/scraper-infra pull request #7
Opened 2023-11-29 23:25 UTC by staclb

Created bank of zambia scraper based on existing kenya example. 
Resolves #29

2023-11-29 23:35 UTC, nattiechan commented
Nice work! The fun challenge becomes - are you confident walking through what the scraper is _actually_ doing? ;)

2023-11-29 23:50 UTC, staclb commented
> Nice work! The fun challenge becomes - are you confident walking through what the scraper is _actually_ doing? ;) Why is the scraper build the way it is? What is with all the `with .....`?

2023-11-30 06:23 UTC, nattiechan requested changes

2023-11-30 06:23 UTC, nattiechan commented on scrapers/bank_of_zambia.py
> +        absolute_url = f"{BASE_URL}{link}"
While reviewing https://github.com/sgoldfarb2/scraper-infra/pull/5, I realized that perhaps it may be good to double-check to ensure `link` has value before continuing. Could we add a check here and also a check in `bank_of_kenya` scraper?

2023-12-01 00:32 UTC, staclb commented on scrapers/bank_of_zambia.py
> +        absolute_url = f"{BASE_URL}{link}"
@nattiechan Implemented the error handling for links with exception handling in mind

2023-12-01 00:35 UTC, nattiechan requested changes

2023-12-01 00:35 UTC, nattiechan commented on scrapers/bank_of_kenya.py
> +            raise ValueError("Invalid link or not found")
Consider the following.

```
link = None
bool(link is None) ---> # True

link = ''
bool(link is None) ---> # False
```

In this case we want to ensure that if we don't have a link we need to stop the script. Moreover, in this case specifically, an empty string should not pass the check either. So we should do:

```suggestion
        if not link or not link.endswith(".pdf"):
            browser.close()
            raise ValueError("Invalid link or not found")
```

or if we want to go a step further:

```suggestion
        if not link or (isinstance(link, str) and not link.endswith(".pdf")):
            browser.close()
            raise ValueError("Invalid link or not found")
```

They both have pros and cons tbh. I will leave you to figure out what the second one may miss that the first one won't, and vice versa.

Though I think for all intents and purposes, let's go with the first suggestion and be more restrictive if we want.

2023-12-01 01:26 UTC, staclb commented on scrapers/bank_of_kenya.py
> +            raise ValueError("Invalid link or not found")
Thank you for the insights, I went ahead and implemented the first case, and I agree that a more strict approach can be introduced later if need be.

2023-12-01 06:13 UTC, nattiechan requested changes
You may want to re-test both scrapers to ensure they work as expected

2023-12-01 06:13 UTC, nattiechan commented on scrapers/bank_of_zambia.py
> +        link = ""
I am guessing this is from you testing? By doing this you are overriding the `link` variable and this scraper should be consistently hitting the error below which is not what we want

2023-12-01 06:13 UTC, nattiechan commented on scrapers/bank_of_zambia.py
> +            raise ValueError("Invalid link or not found")
Since you will need to make some changes anyway, let's clean up the error message here and in the other scraper as well to make it clearer.

```suggestion
        if not link or not link.endswith(".pdf"):
            browser.close()
            raise ValueError("Invalid file URL.")
```

2023-12-01 23:24 UTC, nattiechan approved these changes
Nice work!

2023-12-01 23:39 UTC, jiedong111 approved these changes
Great work, looks good to merge!

2023-12-02 05:39 UTC, merged